import TechSection from "@/components/pages/tech/Tech";

export const metadata = {
  title: "Space IT | Політики конфіденційності",
  description: "Generated by create next app",
};

export default function Tech() {
  return (
    <>
      <TechSection />
    </>
  );
}
